site_name: My Second Brain
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: You Think Darkness Is Your Ally
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to Light Mode
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jtbrown95138/
    - icon: fontawesome/brands/gitlab
      link: https://govcloudsolutions.io

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg



copyright: Copyright &copy; Jamal Brown, PMP, CISSP, CKAD